apiVersion: batch.example.com/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: simple-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  start: 20
  end: 21
  replicas: 8
  deployments:
    - name: dp-api-server
      namespace: dp
    - name: dp-item-server
      namespace: dp